/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Microsoft To Do
 * OpenAPI spec version: 1.0.0
 */
import type { MicrosoftGraphTodoTaskList } from './microsoftGraphTodoTaskList';

/**
 * New navigation property
 */
export type MicrosoftGraphTodoTaskListBody = MicrosoftGraphTodoTaskList;
