/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Microsoft To Do
 * OpenAPI spec version: 1.0.0
 */

export type MicrosoftGraphTodoTaskAllOf = {
  body?: unknown;
  bodyLastModifiedDateTime?: string;
  completedDateTime?: unknown;
  createdDateTime?: string;
  dueDateTime?: unknown;
  importance?: unknown;
  isReminderOn?: boolean;
  lastModifiedDateTime?: string;
  recurrence?: unknown;
  reminderDateTime?: unknown;
  status?: unknown;
  title?: string;
};
