/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Microsoft To Do
 * OpenAPI spec version: 1.0.0
 */
import type { MicrosoftGraphTodoTask } from './microsoftGraphTodoTask';

export type MicrosoftGraphTodoTaskListAllOf = {
  displayName?: string;
  isOwner?: boolean;
  isShared?: boolean;
  wellknownListName?: unknown;
  tasks?: MicrosoftGraphTodoTask[];
};
