/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Microsoft To Do
 * OpenAPI spec version: 1.0.0
 */
import type { MicrosoftGraphEntity } from './microsoftGraphEntity';
import type { MicrosoftGraphTodoTaskListAllOf } from './microsoftGraphTodoTaskListAllOf';

export type MicrosoftGraphTodoTaskList = MicrosoftGraphEntity & MicrosoftGraphTodoTaskListAllOf;
