/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * Swagger Microsoft To Do
 * OpenAPI spec version: 1.0.0
 */

export interface OdataError {
  code?: string;
  message?: string;
  target?: string;
}
