openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Microsoft To Do
servers:
  - url: https://graph.microsoft.com/v1.0/
paths:
  /me/todo/lists:
    get:
      tags:
        - me.todo
      summary: Get lists from me
      operationId: me.todo.ListLists
      responses:
        "200":
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of todoTaskList
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: "#/components/schemas/microsoft.graph.todoTaskList"
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
    post:
      tags:
        - me.todo
      summary: Create new navigation property to lists for me
      operationId: me.todo.CreateLists
      requestBody:
        $ref: "#/components/requestBodies/microsoft.graph.todoTaskList"
      responses:
        "201":
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/microsoft.graph.todoTaskList"
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
  "/me/todo/lists/{todoTaskList-id}":
    get:
      tags:
        - me.todo
      summary: Get lists from me
      operationId: me.todo.GetLists
      parameters:
        - in: path
          name: todoTaskList-id
          description: "key: todoTaskList-id of todoTaskList"
          required: true
          x-ms-docs-key-type: todoTaskList
          schema:
            type: string
      responses:
        "200":
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/microsoft.graph.todoTaskList"
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - me.todo
      summary: Update the navigation property lists in me
      operationId: me.todo.UpdateLists
      parameters:
        - in: path
          name: todoTaskList-id
          description: "key: todoTaskList-id of todoTaskList"
          required: true
          x-ms-docs-key-type: todoTaskList
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/microsoft.graph.todoTaskList"
      responses:
        "204":
          description: Success
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
  "/me/todo/lists/{todoTaskList-id}/tasks":
    get:
      tags:
        - me.todo
      summary: Get tasks from me
      operationId: me.todo.lists.ListTasks
      parameters:
        - in: path
          name: todoTaskList-id
          description: "key: todoTaskList-id of todoTaskList"
          required: true
          x-ms-docs-key-type: todoTaskList
          schema:
            type: string
      responses:
        "200":
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of todoTask
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: "#/components/schemas/microsoft.graph.todoTask"
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
    post:
      tags:
        - me.todo
      summary: Create new navigation property to tasks for me
      operationId: me.todo.lists.CreateTasks
      parameters:
        - in: path
          name: todoTaskList-id
          description: "key: todoTaskList-id of todoTaskList"
          required: true
          x-ms-docs-key-type: todoTaskList
          schema:
            type: string
      requestBody:
        $ref: "#/components/requestBodies/microsoft.graph.todoTask"
      responses:
        "201":
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/microsoft.graph.todoTask"
        default:
          $ref: "#/components/responses/error"
      x-ms-docs-operation-type: operation
components:
  responses:
    error:
      description: error
      content:
        "*/*":
          schema:
            $ref: "#/components/schemas/odata.error"
  schemas:
    odata.error:
      required:
        - error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
      example:
        id: string (identifier)
    microsoft.graph.todoTaskList:
      allOf:
        - $ref: "#/components/schemas/microsoft.graph.entity"
        - title: todoTaskList
          type: object
          properties:
            displayName:
              type: string
            isOwner:
              type: boolean
            isShared:
              type: boolean
            wellknownListName: {}
            tasks:
              type: array
              items:
                $ref: "#/components/schemas/microsoft.graph.todoTask"
      example:
        id: string (identifier)
        displayName: string
        isOwner: true
        isShared: true
        wellknownListName:
          "@odata.type": microsoft.graph.wellknownListName
        extensions:
          - "@odata.type": microsoft.graph.extension
        tasks:
          - "@odata.type": microsoft.graph.todoTask
    microsoft.graph.todoTask:
      allOf:
        - $ref: "#/components/schemas/microsoft.graph.entity"
        - title: todoTask
          type: object
          properties:
            body: {}
            bodyLastModifiedDateTime:
              format: date-time
              pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
              type: string
            completedDateTime: {}
            createdDateTime:
              format: date-time
              pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
              type: string
            dueDateTime: {}
            importance: {}
            isReminderOn:
              type: boolean
            lastModifiedDateTime:
              format: date-time
              pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
              type: string
            recurrence: {}
            reminderDateTime: {}
            status: {}
            title:
              type: string
      example:
        id: string (identifier)
        body:
          "@odata.type": microsoft.graph.itemBody
        bodyLastModifiedDateTime: string (timestamp)
        completedDateTime:
          "@odata.type": microsoft.graph.dateTimeTimeZone
        createdDateTime: string (timestamp)
        dueDateTime:
          "@odata.type": microsoft.graph.dateTimeTimeZone
        importance:
          "@odata.type": microsoft.graph.importance
        isReminderOn: true
        lastModifiedDateTime: string (timestamp)
        recurrence:
          "@odata.type": microsoft.graph.patternedRecurrence
        reminderDateTime:
          "@odata.type": microsoft.graph.dateTimeTimeZone
        status:
          "@odata.type": microsoft.graph.taskStatus
        title: string
        extensions:
          - "@odata.type": microsoft.graph.extension
        linkedResources:
          - "@odata.type": microsoft.graph.linkedResource
  requestBodies:
    microsoft.graph.todoTask:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/microsoft.graph.todoTask"
      description: New navigation property
      required: true
    microsoft.graph.todoTaskList:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/microsoft.graph.todoTaskList"
      description: New navigation property
      required: true